### ISSUE TITLE
ec_sys node doesn't seem to exist on my fedora 40 install

### ISSUE THREAD

**Issue by daeSundae** [alou-S/omen-fan#15]
```
root@fedora:/home/dae/Documents/omen-fan# ./omen-fan.py e start
modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.10.9-200.fc40.x86_64
Traceback (most recent call last):
  File "/home/dae/Documents/omen-fan/./omen-fan.py", line 340, in <module>
    cli()
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dae/Documents/omen-fan/./omen-fan.py", line 249, in service_cli
    load_ec_module()
  File "/home/dae/Documents/omen-fan/./omen-fan.py", line 99, in load_ec_module
    subprocess.run(["modprobe", "ec_sys", "write_support=1"], check=True)
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['modprobe', 'ec_sys', 'write_support=1']' returned non-zero exit status 1.
root@fedora:/home/dae/Documents/omen-fan# 
```

I own an hp victus s0046nt and i wanted to see if this could maybe work in order to increase fan speeds
this is the result i'm getting and i have no clue what to do. Is this because of the distribution i'm using or ec_sys node doesn't exist on my hardware somehow?

**Comment by daeSundae** [comment]
Where else can i find the ec_sys node? I assume even if i were to monitor the values on Windows it wouldn't help on Fedora for me?

**Comment by daeSundae** [comment]
**ec_sys not existing was fixed by installing kernel debug version with:**

`sudo dnf install kernel-debug kernel-debug-core kernel-debug-modules kernel-debug-modules-extra`

but now i ran into another trouble:

```
dae@fedora:~/Documents/omen-fan$ sudo ./omen-fand.py x
Traceback (most recent call last):
  File "/home/dae/Documents/omen-fan/./omen-fand.py", line 90, in <module>
    with open(IPC_FILE, "w", encoding="utf-8") as ipc:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/omen-fand.PID'

```

**Comment by daeSundae** [comment]
Issue fixed by using sudo bash -c command to write to registers instead of sudo echo. There seems to be some difference in permissions or something.
